-- Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
-- The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
-- Then recompile and restart xmonad.

module Colors
    ( wallpaper, sourceColor
    -- Special
    , background, foreground, cursor
    -- Material 3 Primary
    , primary, onPrimary, primaryContainer, onPrimaryContainer
    , primaryFixed, primaryFixedDim, onPrimaryFixed, onPrimaryFixedVariant
    -- Material 3 Secondary
    , secondary, onSecondary, secondaryContainer, onSecondaryContainer
    , secondaryFixed, secondaryFixedDim, onSecondaryFixed, onSecondaryFixedVariant
    -- Material 3 Tertiary
    , tertiary, onTertiary, tertiaryContainer, onTertiaryContainer
    , tertiaryFixed, tertiaryFixedDim, onTertiaryFixed, onTertiaryFixedVariant
    -- Material 3 Error
    , error, onError, errorContainer, onErrorContainer
    -- Material 3 Surface
    , surface, onSurface, surfaceVariant, onSurfaceVariant
    , surfaceDim, surfaceBright
    , surfaceContainerLowest, surfaceContainerLow, surfaceContainer
    , surfaceContainerHigh, surfaceContainerHighest
    -- Material 3 Outline
    , outline, outlineVariant
    -- Material 3 Inverse
    , inverseSurface, inverseOnSurface, inversePrimary
    -- Material 3 Shadow & Scrim
    , shadow, scrim
    -- Terminal Colors
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Generated by WPG-M3 (Material Design 3 Color System)

-- Wallpaper & Source
wallpaper="/home/diaz/Pictures/Wallpapers/purpled-night.jpg"
sourceColor="#6019ad"

-- Special (Compatibility)
background="#16121a"
foreground="#e8dfec"
cursor="#d8b9ff"

-- === MATERIAL 3 PRIMARY ===
primary="#d8b9ff"
onPrimary="#450086"
primaryContainer="#6019ad"
onPrimaryContainer="#cba3ff"
primaryFixed="#eedcff"
primaryFixedDim="#d8b9ff"
onPrimaryFixed="#290054"
onPrimaryFixedVariant="#6019ad"

-- === MATERIAL 3 SECONDARY ===
secondary="#d8bafc"
onSecondary="#3c245b"
secondaryContainer="#563d76"
onSecondaryContainer="#c9aced"
secondaryFixed="#eedcff"
secondaryFixedDim="#d8bafc"
onSecondaryFixed="#260d45"
onSecondaryFixedVariant="#533b73"

-- === MATERIAL 3 TERTIARY ===
tertiary="#ffb4a4"
onTertiary="#630e00"
tertiaryContainer="#8b1901"
onTertiaryContainer="#ff9a83"
tertiaryFixed="#ffdad3"
tertiaryFixedDim="#ffb4a4"
onTertiaryFixed="#3d0600"
onTertiaryFixedVariant="#8b1901"

-- === MATERIAL 3 ERROR ===
error="#ffb4ab"
onError="#690005"
errorContainer="#93000a"
onErrorContainer="#ffdad6"

-- === MATERIAL 3 SURFACE ===
surface="#16121a"
onSurface="#e8dfec"
surfaceVariant="#4b4453"
onSurfaceVariant="#cdc3d5"
surfaceDim="#16121a"
surfaceBright="#3c3741"
surfaceContainerLowest="#100d15"
surfaceContainerLow="#1e1a22"
surfaceContainer="#221e27"
surfaceContainerHigh="#2d2831"
surfaceContainerHighest="#38333c"

-- === MATERIAL 3 OUTLINE ===
outline="#978d9f"
outlineVariant="#4b4453"

-- === MATERIAL 3 INVERSE ===
inverseSurface="#e8dfec"
inverseOnSurface="#332f38"
inversePrimary="#793ac7"

-- === MATERIAL 3 SHADOW & SCRIM ===
shadow="#000000"
scrim="#000000"

-- === TERMINAL COLORS ===
-- Normal Colors
color0="#16121a"   -- Black
color1="#690005"   -- Red
color2="#4b4453"   -- Green
color3="#6019ad"   -- Yellow
color4="#450086"   -- Blue
color5="#38333c"   -- Magenta
color6="#563d76"   -- Cyan
color7="#793ac7"   -- White

-- Bright Colors
color8="#e8dfec"   -- Bright Black
color9="#ffb4ab"   -- Bright Red
color10="#ffdad3" -- Bright Green
color11="#eedcff" -- Bright Yellow
color12="#d8b9ff" -- Bright Blue
color13="#ffb4a4" -- Bright Magenta
color14="#ffb4a4" -- Bright Cyan
color15="#e8dfec" -- Bright White
