#!/bin/bash
# Shell Variables - Generated by WPG-M3
# Material Design 3 Color System

# Wallpaper & Source
wallpaper='/home/diaz/Pictures/Wallpapers/purpled-night.jpg'
source_color='#6019ad'

# Special (Compatibility)
background='#16121a'
foreground='#e8dfec'
cursor='#d8b9ff'

# === MATERIAL 3 PRIMARY ===
primary='#d8b9ff'
on_primary='#450086'
primary_container='#6019ad'
on_primary_container='#cba3ff'
primary_fixed='#eedcff'
primary_fixed_dim='#d8b9ff'
on_primary_fixed='#290054'
on_primary_fixed_variant='#6019ad'

# === MATERIAL 3 SECONDARY ===
secondary='#d8bafc'
on_secondary='#3c245b'
secondary_container='#563d76'
on_secondary_container='#c9aced'
secondary_fixed='#eedcff'
secondary_fixed_dim='#d8bafc'
on_secondary_fixed='#260d45'
on_secondary_fixed_variant='#533b73'

# === MATERIAL 3 TERTIARY ===
tertiary='#ffb4a4'
on_tertiary='#630e00'
tertiary_container='#8b1901'
on_tertiary_container='#ff9a83'
tertiary_fixed='#ffdad3'
tertiary_fixed_dim='#ffb4a4'
on_tertiary_fixed='#3d0600'
on_tertiary_fixed_variant='#8b1901'

# === MATERIAL 3 ERROR ===
error='#ffb4ab'
on_error='#690005'
error_container='#93000a'
on_error_container='#ffdad6'

# === MATERIAL 3 SURFACE ===
surface='#16121a'
on_surface='#e8dfec'
surface_variant='#4b4453'
on_surface_variant='#cdc3d5'
surface_dim='#16121a'
surface_bright='#3c3741'
surface_container_lowest='#100d15'
surface_container_low='#1e1a22'
surface_container='#221e27'
surface_container_high='#2d2831'
surface_container_highest='#38333c'

# === MATERIAL 3 OUTLINE ===
outline='#978d9f'
outline_variant='#4b4453'

# === MATERIAL 3 INVERSE ===
inverse_surface='#e8dfec'
inverse_on_surface='#332f38'
inverse_primary='#793ac7'

# === MATERIAL 3 SHADOW & SCRIM ===
shadow='#000000'
scrim='#000000'

# === TERMINAL COLORS ===
# Normal Colors
color0='#16121a'   # Black
color1='#690005'   # Red
color2='#4b4453'   # Green
color3='#6019ad'   # Yellow
color4='#450086'   # Blue
color5='#38333c'   # Magenta
color6='#563d76'   # Cyan
color7='#793ac7'   # White

# Bright Colors
color8='#e8dfec'   # Bright Black
color9='#ffb4ab'   # Bright Red
color10='#ffdad3' # Bright Green
color11='#eedcff' # Bright Yellow
color12='#d8b9ff' # Bright Blue
color13='#ffb4a4' # Bright Magenta
color14='#ffb4a4' # Bright Cyan
color15='#e8dfec' # Bright White

# === FZF COLORS (Material 3 themed) ===
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:4,fg+:15,bg+:8,hl+:4
    --color info:6,prompt:2,spinner:5,pointer:4,marker:1
    --color border:8,label:7,query:7
    --color gutter:0,separator:8
    --border --prompt='❯ ' --pointer='▶' --marker='✓'
"

# === LS_COLORS (Fix unreadable colors) ===
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"

# === OPTIONAL: Export all M3 colors for use in other scripts ===
export M3_PRIMARY="$primary"
export M3_SECONDARY="$secondary"
export M3_TERTIARY="$tertiary"
export M3_SURFACE="$surface"
export M3_ERROR="$error"
export M3_BACKGROUND="$background"
export M3_FOREGROUND="$foreground"
