#!/bin/sh
# TTY Color Scheme
# Generated by 'wpg-m3' - Material 3 Color Scheme
[ "${TERM:-none}" = "linux" ] && \
    printf '%b' '\e]P0#16121a
                 \e]P1#690005
                 \e]P2#4b4453
                 \e]P3#6019ad
                 \e]P4#450086
                 \e]P5#38333c
                 \e]P6#563d76
                 \e]P7#793ac7
                 \e]P8#e8dfec
                 \e]P9#ffb4ab
                 \e]PA#ffdad3
                 \e]PB#eedcff
                 \e]PC#d8b9ff
                 \e]PD#ffb4a4
                 \e]PE#ffb4a4
                 \e]PF#e8dfec
                 \ec'
