# Shell variables
# Generated by 'wal'
wallpaper='/home/diaz/.config/wpg/wallpapers/road.jpg'

# Special
background='#000000'
foreground='#9a9a9a'
cursor='#9a9a9a'

# Colors
color0='#000000'
color1='#2b2925'
color2='#293847'
color3='#344d4f'
color4='#52524b'
color5='#55738e'
color6='#6c93a6'
color7='#9a9a9a'
color8='#363636'
color9='#2b2925'
color10='#293847'
color11='#344d4f'
color12='#52524b'
color13='#55738e'
color14='#6c93a6'
color15='#9a9a9a'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
